const express = require("express");
const bodyParser = require("body-parser");
const date = require(__dirname +  "/date.js") //requiring a module which is located in current directory with a name "date.js"

//console.log(date); //this would print --> [Function: getDate] which means we are printing that is exported from date.js
//console.log(date()); //this would print value of currentDate coz we are calling date as a function which is nothing but getDate() from date.js

const app = express();
app.set('view engine', 'ejs'); //with this line we are telling app which is generated by express to use ejs as a view engine
app.use(bodyParser.urlencoded({extended:true}));
app.use(express.static("public")); //this is needed to access all static files within our project

let items = []; //creating an array of items here to accept input from user

app.get("/", function(req, res){

  let dayAndDate = date.getDate(); //this is how you access it 

  res.render("list", {dayOfWeek:dayAndDate, items:items});
  //here we are passing 2 parameters
  //1st parameter is name of ejs file
  //2nd Parameter is a javascript object in key-value pair
})

app.post("/", function(req,res){

    listItemFromUser = req.body.newItem;
    items.push(listItemFromUser);
    res.redirect("/");
    //why this redirect added here?
    //so when a user adds new item, it would be redirected to home route
    //console.log(listItemFromUser);

    //res.render("list", {newItemAdded : listItemFromUser});

})


app.listen(3000, function(){
  console.log("server started on port 3000");
})
